name: CI Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-benchmark:
    uses: ./.github/workflows/benchmark.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
