name: Manual Benchmark Run

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to benchmark"
        required: true
        default: "main"

jobs:
  call-benchmark:
    uses: ./.github/workflows/benchmark.yml
    with:
      branch: ${{ github.event.inputs.branch }}
    secrets:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    
