name: CI Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Bencher CLI
        uses: bencherdev/bencher@main

      - name: Run Benchmarks
        run: |
          bencher run \
            --project jace \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch "${{ inputs.branch }}" \
            --testbed ubuntu-latest \
            --threshold-measure latency \
            --threshold-test t_test \
            --threshold-max-sample-size 64 \
            --threshold-upper-boundary 0.99 \
            --thresholds-reset \
            --err \
            --adapter json \
            --github-actions '${{ secrets.GITHUB_TOKEN }}' \
            dotnet run -c Release --project Jace.Benchmark
