# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Manual Build

on:
  workflow_dispatch: 
    inputs: 
      os: 
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
      configuration: 
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release
      branch:
        description: "Branch to run benchmarks on"
        required: true
        default: "master"
      commit:
        description: 'Commit SHA to checkout (leave blank for latest on main)'
        required: false
        default: ''

jobs:
  build-manual:
    environment: manual-workflow
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit || inputs.branch || 'master' }}
          
      - name: Confirm checked out commit
        shell: bash
        run: |
          echo "Checked out ref: ${{ inputs.commit != '' && inputs.commit || inputs.branch }}"
          git log -1 --oneline

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            5.0.x

      - name: Restore solution
        run: dotnet restore Jace.sln

      - name: Build solution
        run: dotnet build Jace.sln -c ${{ inputs.configuration }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ inputs.os }}-${{ inputs.configuration }}
          path: '**/bin/${{ inputs.configuration }}/'
        