name: Test Jace
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: true
    
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        target-framework: [ net6.0, net9.0 ]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and run tests
        run: 
          dotnet test Jace.sln
            -f ${{ matrix.target-framework }}
            --results-directory ./test-results/${{ matrix.target-framework }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.target-framework }}
          path: ./test-results/${{ matrix.target-framework }}
