name: Test Jace
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        target-framework: [ net5.0, net9.0 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            5.0.x

      - name: Restore solution
        run: dotnet restore Jace.sln

      - name: Build and run tests
        # net5.0 doesn't play nice on ubuntu-22.04 onwards. Missing required libssl
        if: ${{ matrix.target-framework != 'net5.0' || matrix.os != 'ubuntu-latest' }}
        run: dotnet test -f ${{ matrix.target-framework }}

      - name: Gather Coverage (Ubuntu net9.0 Only)
        if: ${{ matrix.target-framework == 'net9.0' && matrix.os == 'ubuntu-latest' }}
        id: coverage
        shell: bash
        run: |
          dotnet test ./Jace.Tests/Jace.Tests.csproj \
            -f ${{ matrix.target-framework }} \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./coverage/ \
            /p:CoverletOutputFormat=lcov

      - name: Upload coverage to Codecov
        if: ${{ steps.coverage.outcome == 'success' }} 
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage.${{ matrix.target-framework }}.info
          fail_ci_if_error: true
